# POST http://localhost:8080/category

GET http://localhost:8080/category

###

POST http://localhost:8080/category/add-rest 
Content-Type: application/json

{
    "title": "בשרים",
    "id": "64515a9072e6bfe71dde7419"
}

###

POST http://localhost:8080/category/
Content-Type: application/json

{
    "title": "בשרים",
    "subtitle": "כשר"
}

###
DELETE http://localhost:8080/category/remove-rest
Content-Type: application/json

{
    "title": "בשרים",
    "id": "64515a9072e6bfe71dde7419"
}